### ISSUE TITLE
Set up as GH action

### ISSUE THREAD

**Issue by KevinBatdorf** [bigbite/wp-cypress#49]
**Describe the solution you'd like**
I'm looking for a solution to automate testing of a WP plugin in a GitHub action. 

Ideally, The repo would be of the plugin files only and it would install WP around it, set up the server, etc.

Has anyone set this up before?

**Comment by liamdefty** [comment]
Hi @KevinBatdorf 

We've done this before, so definitely achievable and doesn't require too much work if you're using this tool.

First set your [configuration](https://github.com/bigbite/wp-cypress/wiki#configuration) in `cypress.json` to be something similar to below ensuring the path to the plugin you want to test is correct.

```
{
 "wp": {
    "version": ["5.5"],
    "plugins": ["./"]
  }
}
```

Then you can use Cypress's GitHub action https://github.com/cypress-io/github-action to get most of the way there. But you need to ensure the test container is running. We've done something similar below in a workflow:

```yml
      - name: Yarn Install
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false

      - name: WP Cypress Start
        run: yarn run wp-cypress start

      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          install: false
```

We hope to provide some examples of testing on different CI's in the future but hope this helps for now 🤞🏽
